# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\katr4\PycharmProjects\process_analyzer\app\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.processBox = QtWidgets.QGroupBox(self.centralwidget)
        self.processBox.setGeometry(QtCore.QRect(10, 10, 281, 581))
        self.processBox.setObjectName("processBox")
        self.processList = QtWidgets.QListWidget(self.processBox)
        self.processList.setGeometry(QtCore.QRect(10, 20, 261, 551))
        self.processList.setObjectName("processList")
        self.threadBox = QtWidgets.QGroupBox(self.centralwidget)
        self.threadBox.setGeometry(QtCore.QRect(300, 10, 491, 271))
        self.threadBox.setObjectName("threadBox")
        self.threadList = QtWidgets.QListWidget(self.threadBox)
        self.threadList.setGeometry(QtCore.QRect(10, 20, 471, 241))
        self.threadList.setObjectName("threadList")
        self.informationBox = QtWidgets.QGroupBox(self.centralwidget)
        self.informationBox.setGeometry(QtCore.QRect(300, 290, 491, 301))
        self.informationBox.setObjectName("informationBox")
        self.infromationText = QtWidgets.QPlainTextEdit(self.informationBox)
        self.infromationText.setGeometry(QtCore.QRect(10, 20, 471, 271))
        self.infromationText.setObjectName("infromationText")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.processBox.setTitle(_translate("MainWindow", "Processes"))
        self.threadBox.setTitle(_translate("MainWindow", "Threads"))
        self.informationBox.setTitle(_translate("MainWindow", "Information"))
