# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\katr4\PycharmProjects\process_analyzer\app\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1449, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.processBox = QtWidgets.QGroupBox(self.centralwidget)
        self.processBox.setGeometry(QtCore.QRect(10, 10, 1431, 381))
        self.processBox.setObjectName("processBox")
        self.tableWidget = QtWidgets.QTableWidget(self.processBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 1411, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.informationBox = QtWidgets.QGroupBox(self.centralwidget)
        self.informationBox.setGeometry(QtCore.QRect(170, 400, 1101, 331))
        self.informationBox.setObjectName("informationBox")
        self.treeWidget = QtWidgets.QTreeWidget(self.informationBox)
        self.treeWidget.setGeometry(QtCore.QRect(10, 20, 1081, 301))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Process analyzer", "Process analyzer"))
        self.processBox.setTitle(_translate("Process analyzer", "Processes"))
        self.informationBox.setTitle(_translate("Process analyzer", "DLLs"))
